# 解决数据连接失败问题
import pymysql

pymysql.install_as_MySQLdb()
